# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml

name: comp-hiclip-dev
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::pigz=2.3.4
  - bioconda::fastqc=0.11.9
  - bioconda::cutadapt=3.2
  - bioconda::star=2.7.7a
  - bioconda::bbmap=38.87
  - bioconda::pblat=2.5
  - bioconda::bedtools=2.29.2
  - bioconda::umi_tools=1.1.1
  - bioconda::samtools=1.11
  - bioconda::viennarna=2.4.17
  - bioconda::forgi=2.0.3
  - pysam
  - pandas

# R packages
  - conda-forge::r-base
  - conda-forge::r-devtools
  - conda-forge::r-data.table
  - conda-forge::r-r.utils
  - conda-forge::r-ggplot2
  - conda-forge::r-scales
  - conda-forge::r-tictoc
  - conda-forge::r-optparse
  - conda-forge::r-rslurm
  - conda-forge::r-cowplot
  - conda-forge::r-ggthemes
  - bioconda::bioconductor-rtracklayer
  - bioconda::bioconductor-rbgl
  - bioconda::bioconductor-graph